# Generated by Django 5.0.6 on 2026-09-23 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'کسب\u200cوکار', 'verbose_name_plural': 'کسب\u200cوکارها'},
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(default='USD', max_length=8, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(choices=[('general', 'عمومی'), ('retail', 'خرده\u200cفروشی'), ('catering', 'خدمات غذایی و پذیرایی'), ('services', 'خدمات حرفه\u200cای'), ('wholesale', 'عمده\u200cفروشی / توزیع'), ('manufacturing', 'تولید'), ('other', 'سایر')], default='general', max_length=30, verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
