# Generated by Django 5.0.6 on 2026-09-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ['-created_at'], 'verbose_name': 'یادداشت مشتری', 'verbose_name_plural': 'یادداشت\u200cهای مشتری'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='مسئول'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ارزش تخمینی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('referral', 'معرفی'), ('website', 'وب\u200cسایت'), ('social', 'شبکه\u200cهای اجتماعی'), ('cold_outreach', 'تماس سرد'), ('event', 'رویداد'), ('other', 'سایر')], max_length=30, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('lead', 'سرنخ'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='lead', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.CharField(blank=True, help_text='برچسب\u200cها را با ویرگول جدا کنید', max_length=300, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='body',
            field=models.TextField(verbose_name='متن یادداشت'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='tenants.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer', verbose_name='مشتری'),
        ),
    ]
