# Generated by Django 5.0.6 on 2026-09-29 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_alter_salesreturn_options'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ اولیه')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ نهایی')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.business', verbose_name='کسب\u200cوکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='finance_inv_busines_d4c39a_idx'), models.Index(fields=['business', 'created_at'], name='finance_inv_busines_12e50e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='unique_invoice_number_per_business'),
        ),
    ]
