# Generated by Django 5.0.6 on 2026-09-29 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ پرداخت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتخوان'), ('bank_transfer', 'انتقال بانکی'), ('online', 'آنلاین'), ('other', 'سایر')], max_length=30, verbose_name='روش پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('paid_at', models.DateTimeField(verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.business', verbose_name='کسب\u200cوکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['business', 'paid_at'], name='finance_pay_busines_f8f113_idx'), models.Index(fields=['business', 'invoice'], name='finance_pay_busines_9affda_idx')],
            },
        ),
    ]
