# Generated by Django 5.0.6 on 2026-09-29 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان هزینه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('expense_date', models.DateField(verbose_name='تاریخ هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.business', verbose_name='کسب\u200cوکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['business', 'expense_date'], name='finance_exp_busines_befa91_idx'), models.Index(fields=['business', 'category'], name='finance_exp_busines_6028d4_idx')],
            },
        ),
    ]
