# Generated by Django 5.0.6 on 2026-09-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_alter_product_options_and_more'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=50, verbose_name='کد انبار')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='انبار پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='inventory_w_busines_dc55d5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('business', 'code'), name='unique_warehouse_code_per_business'),
        ),
    ]
