# Generated by Django 5.0.6 on 2026-09-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='موجودی')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='حد سفارش مجدد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='inventory.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبارها',
                'indexes': [models.Index(fields=['warehouse', 'product'], name='inventory_w_warehou_bf2f17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_product_per_warehouse'),
        ),
    ]
