# Generated by Django 5.0.6 on 2026-09-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_warehouse_warehousestock_and_more'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام تأمین\u200cکننده')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='نام شرکت')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='شناسه مالیاتی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'تأمین\u200cکننده',
                'verbose_name_plural': 'تأمین\u200cکنندگان',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='inventory_s_busines_47c58a_idx')],
            },
        ),
    ]
