# Generated by Django 5.0.6 on 2026-09-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=50, verbose_name='شماره خرید')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('ordered', 'سفارش داده شده'), ('received', 'دریافت شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tenants.business', verbose_name='کسب\u200cوکار')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier', verbose_name='تأمین\u200cکننده')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='inventory_p_busines_c58b41_idx'), models.Index(fields=['business', 'purchase_date'], name='inventory_p_busines_88b681_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('business', 'purchase_number'), name='unique_purchase_number_per_business'),
        ),
    ]
