# Generated by Django 5.0.6 on 2026-09-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='تعداد')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='محصول')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='خرید')),
            ],
            options={
                'verbose_name': 'آیتم خرید',
                'verbose_name_plural': 'آیتم\u200cهای خرید',
                'ordering': ['id'],
            },
        ),
    ]
