# Generated by Django 5.0.6 on 2026-09-28 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseitem'),
        ('tenants', '0002_alter_business_options_alter_business_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل انتقال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='tenants.business', verbose_name='کسب\u200cوکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='inventory.warehouse', verbose_name='انبار مقصد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='inventory.product', verbose_name='محصول')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='inventory.warehouse', verbose_name='انبار مبدأ')),
            ],
            options={
                'verbose_name': 'انتقال موجودی',
                'verbose_name_plural': 'انتقال\u200cهای موجودی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='inventory_s_busines_942508_idx'), models.Index(fields=['business', 'created_at'], name='inventory_s_busines_8b6c18_idx')],
            },
        ),
    ]
