# Generated by Django 5.0.6 on 2026-09-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20),
        ),
    ]
