# Generated by Django 5.0.6 on 2026-09-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesreturn_completed_at_salesreturn_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'verbose_name': 'فروش مرجوع شده', 'verbose_name_plural': 'فروش های مرجوع شده'},
        ),
    ]
